name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and run the Docker image
      run: docker build . --file Dockerfile.minimal --tag soft_hsm_cpp && docker run soft_hsm_cpp

